# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'store_designe.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 500)
        MainWindow.setMinimumSize(QtCore.QSize(800, 500))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(45, 45, 45);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_fram = QtWidgets.QFrame(self.centralwidget)
        self.top_fram.setMaximumSize(QtCore.QSize(16777215, 32))
        self.top_fram.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.top_fram.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top_fram.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_fram.setObjectName("top_fram")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.top_fram)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_3 = QtWidgets.QFrame(self.top_fram)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setStyleSheet("background-color: rgb(52, 101, 164);\n"
"border-radius:10px;\n"
"")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_8.addWidget(self.label_4, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addWidget(self.frame_3)
        self.frame = QtWidgets.QFrame(self.top_fram)
        self.frame.setEnabled(True)
        self.frame.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(0, 92, 157);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.min_button = QtWidgets.QPushButton(self.frame)
        self.min_button.setMaximumSize(QtCore.QSize(33, 32))
        self.min_button.setStyleSheet("border:0px;\n"
"")
        self.min_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("cil-window-minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.min_button.setIcon(icon)
        self.min_button.setObjectName("min_button")
        self.horizontalLayout_3.addWidget(self.min_button)
        self.max_button = QtWidgets.QPushButton(self.frame)
        self.max_button.setMaximumSize(QtCore.QSize(33, 32))
        self.max_button.setStyleSheet("border:0px;\n"
"")
        self.max_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("cil-window-maximize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.max_button.setIcon(icon1)
        self.max_button.setObjectName("max_button")
        self.horizontalLayout_3.addWidget(self.max_button)
        self.close_button = QtWidgets.QPushButton(self.frame)
        self.close_button.setEnabled(True)
        self.close_button.setMaximumSize(QtCore.QSize(33, 32))
        self.close_button.setStyleSheet("QPushButton{\n"
"border:0px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(250,0 , 0);\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("cil-x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_button.setIcon(icon2)
        self.close_button.setObjectName("close_button")
        self.horizontalLayout_3.addWidget(self.close_button)
        self.horizontalLayout.addWidget(self.frame)
        self.verticalLayout.addWidget(self.top_fram)
        self.main_fram = QtWidgets.QFrame(self.centralwidget)
        self.main_fram.setStyleSheet("background-color: rgb(45, 45, 45);")
        self.main_fram.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_fram.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_fram.setObjectName("main_fram")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.main_fram)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.left_fram = QtWidgets.QFrame(self.main_fram)
        self.left_fram.setMaximumSize(QtCore.QSize(55, 16777215))
        self.left_fram.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.left_fram.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_fram.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_fram.setObjectName("left_fram")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.left_fram)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.left_fram)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 38))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.toggel_button = QtWidgets.QPushButton(self.frame_2)
        self.toggel_button.setMaximumSize(QtCore.QSize(130, 35))
        self.toggel_button.setStyleSheet("QPushButton{\n"
"border:0px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 92, 157);\n"
"}")
        self.toggel_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("cil-menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toggel_button.setIcon(icon3)
        self.toggel_button.setIconSize(QtCore.QSize(20, 20))
        self.toggel_button.setObjectName("toggel_button")
        self.horizontalLayout_4.addWidget(self.toggel_button)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_4 = QtWidgets.QFrame(self.left_fram)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_5 = QtWidgets.QLabel(self.frame_6)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_10.addWidget(self.label_5)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 200))
        self.frame_7.setStyleSheet("color:white;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.button_product = QtWidgets.QPushButton(self.frame_7)
        self.button_product.setMaximumSize(QtCore.QSize(130, 35))
        self.button_product.setStyleSheet("QPushButton{\n"
"border:0px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 92, 157);\n"
"}")
        self.button_product.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("product.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_product.setIcon(icon4)
        self.button_product.setIconSize(QtCore.QSize(32, 32))
        self.button_product.setObjectName("button_product")
        self.verticalLayout_4.addWidget(self.button_product)
        self.button_cart = QtWidgets.QPushButton(self.frame_7)
        self.button_cart.setMaximumSize(QtCore.QSize(130, 35))
        self.button_cart.setStyleSheet("QPushButton{\n"
"border:0px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 92, 157);\n"
"}")
        self.button_cart.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("cart.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_cart.setIcon(icon5)
        self.button_cart.setIconSize(QtCore.QSize(32, 32))
        self.button_cart.setObjectName("button_cart")
        self.verticalLayout_4.addWidget(self.button_cart)
        self.button_file = QtWidgets.QPushButton(self.frame_7)
        self.button_file.setMaximumSize(QtCore.QSize(130, 35))
        self.button_file.setStyleSheet("QPushButton{\n"
"border:0px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 92, 157);\n"
"}")
        self.button_file.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("File.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_file.setIcon(icon6)
        self.button_file.setIconSize(QtCore.QSize(32, 32))
        self.button_file.setObjectName("button_file")
        self.verticalLayout_4.addWidget(self.button_file)
        self.button_support = QtWidgets.QPushButton(self.frame_7)
        self.button_support.setMaximumSize(QtCore.QSize(130, 35))
        self.button_support.setStyleSheet("QPushButton{\n"
"border:0px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 92, 157);\n"
"}")
        self.button_support.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("support.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_support.setIcon(icon7)
        self.button_support.setIconSize(QtCore.QSize(32, 32))
        self.button_support.setObjectName("button_support")
        self.verticalLayout_4.addWidget(self.button_support)
        self.bottun_account = QtWidgets.QPushButton(self.frame_7)
        self.bottun_account.setMinimumSize(QtCore.QSize(0, 0))
        self.bottun_account.setMaximumSize(QtCore.QSize(130, 35))
        self.bottun_account.setStyleSheet("QPushButton{\n"
"border:0px;\n"
"color:white;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 92, 157);\n"
"}")
        self.bottun_account.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("User.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bottun_account.setIcon(icon8)
        self.bottun_account.setIconSize(QtCore.QSize(32, 32))
        self.bottun_account.setObjectName("bottun_account")
        self.verticalLayout_4.addWidget(self.bottun_account)
        self.verticalLayout_3.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.frame_4)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_11 = QtWidgets.QFrame(self.frame_8)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_6.addWidget(self.frame_11)
        self.frame_12 = QtWidgets.QFrame(self.frame_8)
        self.frame_12.setMaximumSize(QtCore.QSize(16777215, 85))
        self.frame_12.setStyleSheet("border:0px;")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.button_add = QtWidgets.QPushButton(self.frame_12)
        self.button_add.setStyleSheet("QPushButton:hover{\n"
"background-color: rgb(0, 92, 157);\n"
"}")
        self.button_add.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("add_product.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_add.setIcon(icon9)
        self.button_add.setIconSize(QtCore.QSize(16, 28))
        self.button_add.setObjectName("button_add")
        self.verticalLayout_7.addWidget(self.button_add)
        self.button_remove = QtWidgets.QPushButton(self.frame_12)
        self.button_remove.setStyleSheet("QPushButton:hover{\n"
"background-color: rgb(0, 92, 157);\n"
"}")
        self.button_remove.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("remove_product.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_remove.setIcon(icon10)
        self.button_remove.setIconSize(QtCore.QSize(16, 28))
        self.button_remove.setObjectName("button_remove")
        self.verticalLayout_7.addWidget(self.button_remove)
        self.button_edit = QtWidgets.QPushButton(self.frame_12)
        self.button_edit.setStyleSheet("QPushButton:hover{\n"
"background-color: rgb(0, 92, 157);\n"
"}")
        self.button_edit.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("edit_product.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_edit.setIcon(icon11)
        self.button_edit.setIconSize(QtCore.QSize(16, 28))
        self.button_edit.setObjectName("button_edit")
        self.verticalLayout_7.addWidget(self.button_edit)
        self.verticalLayout_6.addWidget(self.frame_12)
        self.verticalLayout_3.addWidget(self.frame_8)
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 35))
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.button_setting = QtWidgets.QPushButton(self.frame_5)
        self.button_setting.setMaximumSize(QtCore.QSize(130, 35))
        self.button_setting.setStyleSheet("QPushButton{\n"
"border:0px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 92, 157);\n"
"}")
        self.button_setting.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("cil-settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_setting.setIcon(icon12)
        self.button_setting.setIconSize(QtCore.QSize(32, 32))
        self.button_setting.setObjectName("button_setting")
        self.horizontalLayout_5.addWidget(self.button_setting)
        self.verticalLayout_3.addWidget(self.frame_5)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.horizontalLayout_2.addWidget(self.left_fram)
        self.page = QtWidgets.QFrame(self.main_fram)
        self.page.setEnabled(True)
        self.page.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.page.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.page.setFrameShadow(QtWidgets.QFrame.Raised)
        self.page.setObjectName("page")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_9 = QtWidgets.QFrame(self.page)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_9)
        self.stackedWidget.setObjectName("stackedWidget")
        self.product = QtWidgets.QWidget()
        self.product.setObjectName("product")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.product)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.mytable = QtWidgets.QTableWidget(self.product)
        self.mytable.setObjectName("mytable")
        self.mytable.setColumnCount(5)
        self.mytable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Yrsa")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.mytable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Yrsa")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.mytable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Yrsa")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.mytable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Yrsa")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.mytable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Yrsa")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.mytable.setHorizontalHeaderItem(4, item)
        self.horizontalLayout_11.addWidget(self.mytable)
        self.stackedWidget.addWidget(self.product)
        self.cart = QtWidgets.QWidget()
        self.cart.setObjectName("cart")
        self.stackedWidget.addWidget(self.cart)
        self.file = QtWidgets.QWidget()
        self.file.setObjectName("file")
        self.stackedWidget.addWidget(self.file)
        self.about = QtWidgets.QWidget()
        self.about.setObjectName("about")
        self.stackedWidget.addWidget(self.about)
        self.account = QtWidgets.QWidget()
        self.account.setObjectName("account")
        self.stackedWidget.addWidget(self.account)
        self.setting = QtWidgets.QWidget()
        self.setting.setObjectName("setting")
        self.stackedWidget.addWidget(self.setting)
        self.horizontalLayout_7.addWidget(self.stackedWidget)
        self.verticalLayout_5.addWidget(self.frame_9)
        self.frame_10 = QtWidgets.QFrame(self.page)
        self.frame_10.setMaximumSize(QtCore.QSize(16777215, 20))
        self.frame_10.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.frame_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.frame_10)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3, 0, QtCore.Qt.AlignRight)
        self.label_6 = QtWidgets.QLabel(self.frame_10)
        self.label_6.setStyleSheet("color:#729fcf;")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.label = QtWidgets.QLabel(self.frame_10)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label, 0, QtCore.Qt.AlignRight)
        self.label_8 = QtWidgets.QLabel(self.frame_10)
        self.label_8.setStyleSheet("color:#729fcf;")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.label_7 = QtWidgets.QLabel(self.frame_10)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7, 0, QtCore.Qt.AlignRight)
        self.label_2 = QtWidgets.QLabel(self.frame_10)
        self.label_2.setStyleSheet("color:#729fcf;")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.verticalLayout_5.addWidget(self.frame_10)
        self.horizontalLayout_2.addWidget(self.page)
        self.verticalLayout.addWidget(self.main_fram)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">&nbsp;my</span><span style=\" font-size:16pt; color:#2e3436;\">Store &nbsp;&nbsp;</span></p></body></html>"))
        item = self.mytable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.mytable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Discripe"))
        item = self.mytable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Price"))
        item = self.mytable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Type"))
        item = self.mytable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Stock"))
        self.label_3.setText(_translate("MainWindow", "message : "))
        self.label_6.setText(_translate("MainWindow", "no thing"))
        self.label.setText(_translate("MainWindow", "select : "))
        self.label_8.setText(_translate("MainWindow", "0"))
        self.label_7.setText(_translate("MainWindow", "item: "))
        self.label_2.setText(_translate("MainWindow", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
